services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-tracker-api
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/task_tracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TASK_LIST_CACHE_TTL_SECONDS: 300
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-rfbuirfbrufbfjkbskjfblifuequiewurfbrfADekewfbkjcsudwsdcsdhfjbwr87qgiq7r8390er8hwfbf8}
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task-tracker-frontend
    depends_on:
      - app
    ports:
      - "3000:80"
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    container_name: task-tracker-postgres
    environment:
      POSTGRES_DB: task_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d task_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: task-tracker-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
