spring.application.name=task-tracker

server.port=8080

#DB Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/task_tracker}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api/v1

jwt.secretKey=${JWT_SECRET_KEY:rfbuirfbrufbfjkbskjfblifuequiewurfbrf?AD!ekewfbkjcsudwsdcsdhfjbwr87qgiq7r8390er8hwfbf8}

# Redis cache configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.repositories.enabled=false
app.cache.task-list-ttl-seconds=${TASK_LIST_CACHE_TTL_SECONDS:300}
